// Generated by LiveScript 1.2.0
(function(){
  var BaseRobot;
  importScripts('log.js');
  BaseRobot = (function(){
    BaseRobot.displayName = 'BaseRobot';
    var prototype = BaseRobot.prototype, constructor = BaseRobot;
    function BaseRobot(name){
      var this$ = this;
      this.name = name != null ? name : "base-robot";
      this.event_counter = 0;
      this.callbacks = {};
      self.onmessage = function(e){
        return this$.receive(e.data);
      };
    }
    prototype.move_forwards = function(distance, callback){
      callback == null && (callback = null);
      return this.send({
        "action": "move_forwards",
        "amount": distance
      }, callback);
    };
    prototype.move_backwards = function(distance, callback){
      callback == null && (callback = null);
      return this.send({
        "action": "move_backwards",
        "amount": distance
      }, callback);
    };
    prototype.turn_left = function(angle, callback){
      callback == null && (callback = null);
      return this.send({
        "action": "turn_left",
        "amount": angle
      }, callback);
    };
    prototype.turn_right = function(angle, callback){
      callback == null && (callback = null);
      return this.send({
        "action": "turn_right",
        "amount": angle
      }, callback);
    };
    prototype.receive = function(msg){
      var msg_obj;
      msg_obj = JSON.parse(msg);
      switch (msg_obj["action"]) {
      case "run":
        this._run();
        break;
      case "callback":
        logger.log('callback');
        logger.log(this.event_counter);
        if (typeof this.callbacks[msg_obj["event_id"]] === "function") {
          this.callbacks[msg_obj["event_id"]]();
        }
        this.event_counter--;
        if (this.event_counter === 0) {
          this._run();
        }
        break;
      case "interruption":
        logger.log('interruption');
        logger.log(this.event_counter);
        this.event_counter = 0;
        if (msg_obj["status"].wallCollide) {
          this.onWallCollide();
        }
        this._run();
      }
    };
    prototype._run = function(){
      var this$ = this;
      logger.log(this.event_counter);
      return setTimeout(function(){
        return this$.onIdle();
      }, 0);
    };
    prototype.onIdle = function(){
      throw "You need to implement the onIdle() method";
    };
    prototype.onWallCollide = function(){
      throw "You need to implement the onWallCollide() method";
    };
    prototype.send = function(msg_obj, callback){
      var event_id;
      logger.log('send' + " " + msg_obj.action);
      event_id = this.event_counter++;
      this.callbacks[event_id] = callback;
      msg_obj["event_id"] = event_id;
      return postMessage(JSON.stringify(msg_obj));
    };
    return BaseRobot;
  }());
  this.BaseRobot = BaseRobot;
}).call(this);
