// Generated by LiveScript 1.2.0
(function(){
  var TestRobot1, tr;
  importScripts('base-robot.js');
  TestRobot1 = (function(superclass){
    var prototype = extend$((import$(TestRobot1, superclass).displayName = 'TestRobot1', TestRobot1), superclass).prototype, constructor = TestRobot1;
    prototype.onIdle = function(){
      this.move_forwards(30);
      this.move_backwards(30);
      this.turn_left(30);
      return this.turn_right(30);
    };
    prototype.onWallCollide = function(){
      this.move_backwards(10);
      return this.turn_left(90);
    };
    function TestRobot1(){
      TestRobot1.superclass.apply(this, arguments);
    }
    return TestRobot1;
  }(BaseRobot));
  tr = new TestRobot1("My first test robot");
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
