// Generated by LiveScript 1.2.0
(function(){
  var Boss0, tr;
  importScripts('../base-robot.js');
  Boss0 = (function(superclass){
    var prototype = extend$((import$(Boss0, superclass).displayName = 'Boss0', Boss0), superclass).prototype, constructor = Boss0;
    prototype.onIdle = function(){
      this.turn_turret_right(45);
    };
    prototype.onWallCollide = function(){};
    prototype.onHit = function(){
      this.yell("Oops!");
    };
    prototype.onEnemySpot = function(){
      this.yell("Fire!");
      this.shoot();
    };
    function Boss0(){
      Boss0.superclass.apply(this, arguments);
    }
    return Boss0;
  }(BaseRobot));
  tr = new Boss0("Boss 0");
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
