// Generated by LiveScript 1.2.0
(function(){
  var Boss1, tr;
  importScripts('../base-robot.js');
  Boss1 = (function(superclass){
    var prototype = extend$((import$(Boss1, superclass).displayName = 'Boss1', Boss1), superclass).prototype, constructor = Boss1;
    prototype.onIdle = function(){
      this.shoot();
      this.move_forwards(50);
      this.move_backwards(50);
      this.turn_turret_right(180);
      this.shoot();
    };
    prototype.onWallCollide = function(){
      this.move_opposide(10);
      this.turn_left(90);
      this.move_forwards(100);
    };
    prototype.onHit = function(){
      this.yell("Oops!");
      this.move_backwards(100);
      this.shoot();
    };
    prototype.onEnemySpot = function(){
      this.yell("Fire!");
      this.shoot();
    };
    function Boss1(){
      Boss1.superclass.apply(this, arguments);
    }
    return Boss1;
  }(BaseRobot));
  tr = new Boss1("Boss 1");
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
